### ISSUE TITLE
login and password in code

### ISSUE THREAD

**Issue by kocunop** [harshsc2007/Atarbls-Modern-Antivirus#12]
Hello!

it's a bad idea

```
sender_email = "harshantivirus2@gmail.com"
receiver_email = email
password = "gpmohnfvtaxlrglu"
```
see 
https://www.nuitka.net/ 
https://github.com/Falldog/pyconcrete
https://cython.org/

**Comment by HarshscGithub** [comment]
I don't understand what do you mean sir. Please can you elaborate. And sorry for delayed reply.

**Comment by kocunop** [comment]
https://github.com/HarshscGithub/Atarbals-Modern-Antivirus/blob/Main/Atarbals-Antivirus-Installer.py#L363

**Comment by kocunop** [comment]
nuitka, pyconcrete can help you protect source code

**Comment by HarshscGithub** [comment]
Can you show me sir/mam how can I do it. I visited those website but I found no directly related code.
